### ISSUE TITLE
get voltage function in loop without obd

### ISSUE THREAD

**Issue by hayden-t** [stanleyhuangyc/Freematics#10]
Hi, in commit 4efef6855a0a966cac896e194c1c626e303090e8 you uncommented 
```
    int v = logger.getVoltage();
    logger.logData(PID_BATTERY_VOLTAGE, v);
```

this is in the loop without any checks to see if obd active or not, this it is constantly being run and logged with an incorrect voltage ~ 0.398v

likely it doesnt need to be checked this regularly either

also curious why it needs its own function and isnt collected by logger.logOBDData();

**Comment by stanleyhuangyc** [comment]
This will not cause OBD-II connection
      at all.
      
      On 2015/4/4 17:11, hayden-t wrote:
    
    
      Hi, in commit 4efef68 you uncommented 
          int v = logger.getVoltage();
    logger.logData(PID_BATTERY_VOLTAGE, v);

      this is in the loop without any checks to see if obd active or
        not, this it is constantly being run and logged with an
        incorrect voltage ~ 0.398v
      likely it doesnt need to be checked this regularly either
      also curious why it needs its own function and isnt collected
        by logger.logOBDData();
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by stanleyhuangyc** [comment]
This will not cause OBD-II connection at all. It's a function provided by the data logger itself.

**Comment by hayden-t** [comment]
what i meant is that it is still trying to send ODB requests and interpret them regardless of if the ODB is connected or not.
```
int COBD::getVoltage()
{
    char buf[OBD_RECV_BUF_SIZE];
    write("ATRV\r");
    byte n = receive(buf, 100);
```

**Comment by stanleyhuangyc** [comment]
ATRV command is a custom command we implement which does not initiate any OBD-II communication

**Comment by hayden-t** [comment]
so where is write("ATRV\r"); sending to ?

**Comment by stanleyhuangyc** [comment]
The battery voltage meter and GPS is provided by the data logger hardware itself instead of vehicle ECU.

**Comment by hayden-t** [comment]
Ok then why query it if its not connected ? (the battery voltage meter that is)

**Comment by stanleyhuangyc** [comment]
No OBD connection does not mean physically disconnected. This typically happens when ignition is off.

**Comment by hayden-t** [comment]
So are you saying its sampling the cars battery voltage from obd port pins other than the can bus ?

**Comment by stanleyhuangyc** [comment]
Yes I meant that.

**Comment by hayden-t** [comment]
ah ok, i get it now. though im thinking it should still have a config.h define to opt out if you dont want it filling up your logs ? like you do for the MEMS sensor. as i imagine it will be logging constantly even if the car is off ?

**Comment by stanleyhuangyc** [comment]
The sketch is provided as a demo/testing purpose. So it is good to let something work (LED flashing) even if OBD/GPS/MEMS is absent.

**Comment by hayden-t** [comment]
MEMS is always present ? and what do you mean demo/testing purposes ? its the only datalogger sketch that you provide ?

**Comment by hayden-t** [comment]
Also it can still be on by default like the it now and the MEMS is too, but there should be an option to turn it off in config.h

**Comment by hayden-t** [comment]
actually what would be even better would be to be able to specify the poll frequency as well
