### ISSUE TITLE
Error during compilation of latest telelogger

### ISSUE THREAD

**Issue by obat-edgeminds** [stanleyhuangyc/Freematics#101]
Hi,
During compilation of firmware_v5/telelogger with Freematics Builder 1.1.3 I get a -4 error code while compiling teleclient.cpp with something related to HTTP_GET :

`C:\Users\obat\telelogger\teleclient.cpp: In member function 'virtual bool TeleClientHTTP::transmit(const char*, unsigned int)':
C:\Users\obat\telelogger\teleclient.cpp:257:18: error: 'HTTP_GET' was not declared in this scope
   ret = net.send(HTTP_GET, url, true)`

Am I the only one ?

**Comment by stanleyhuangyc** [comment]
Library not update-to-date as sketch.
