### ISSUE TITLE
OBD II when is diconected crash ESP loop

### ISSUE THREAD

**Issue by rosenvladimirov** [stanleyhuangyc/Freematics#131]
Hire is fiix:

#if ENABLE_OBD
  if (sys.devType > 12) {
    batteryVoltage = (float)(analogRead(A0) * 12 * 370) / 4095;
  } else if (state.check(STATE_OBD_READY)) {
    batteryVoltage = obd.getVoltage() * 100;
  }
  if (batteryVoltage) {
    buffer->add(PID_BATTERY_VOLTAGE, (int)batteryVoltage);
  }
#endif

**Comment by stanleyhuangyc** [comment]
Thanks. Will include it.
