### ISSUE TITLE
protocol J1939 not suppport by chip ELM327 v 1.5 /STM32F 

### ISSUE THREAD

**Issue by maicollbellpi** [stanleyhuangyc/Freematics#149]
Hola Stanley, soy Maicoll de Bellpi, Colombia. hace unos meses te compramos un dispositivo Freematics ONE+ Model H, que, según la pagina web, soporta el protocolo J1939. revisando tu código y la electrónica del dispositivo, encontré la referencia del chip que controla la etapa de comunicación entre la ESP32 y el CAN BUS del vehículo, este chip se llama ELM327 v 1.5, sin embargo, el datasheet que ofrece el fabricante de este chip, menciona que nunca a desarrollado esta versión del chip. Por lo que decidí a realizar pruebas con tu dispositivo, intercambiando los protocolos que dice soportar, en el config.h y el OBD.h del telelogger.ino Firmware_v.5, testeando desde el 0x1 hasta el 0xC, enviando al chip STM32 el  comando: AT SP h, para configurar el chip al protocolo seleccionado, las pruebas realizadas te las adjunto, para que valide lo que te menciono.

debido a que el chip no soporta el protocolo j1939, el ejemplo de J1939_monitor, no entrega resultados.

[Documento.pdf](https://github.com/stanleyhuangyc/Freematics/files/7179782/Documento.pdf)
[ELM327DSL.pdf](https://github.com/stanleyhuangyc/Freematics/files/7179794/ELM327DSL.pdf)

agradezco tu ayuda, sí tienes otro chip que sea compatible con el protocolo J1939

**Comment by maicollbellpi** [comment]
[Documento.pdf](https://github.com/stanleyhuangyc/Freematics/files/7179777/Documento.pdf)

**Comment by stanleyhuangyc** [comment]
Refer to j1939_monitor example
