### ISSUE TITLE
Downloading sim800 library

### ISSUE THREAD

**Issue by Pritha01** [stanleyhuangyc/Freematics#16]
Hello everyone!

Can anybody plz help me in downloading "sim800" library. I am unable to find my way.

**Comment by nodemand** [comment]
You have to move up a couple of folders and then download the entire project (as a zip) of which the sim800 library is a part.

**Comment by Pritha01** [comment]
I have downloaded .ZIP file from [https://github.com/stanleyhuangyc/Freematics](url) named "Freematics-master.zip" but when I am trying to add it to Arduino IDLE it shows "specified folder/zip file does not contain a valid library".

![capture](https://cloud.githubusercontent.com/assets/18260878/14281869/3e9e6b1c-fb59-11e5-8434-aea591743c16.JPG)
![capture1](https://cloud.githubusercontent.com/assets/18260878/14281879/4a5d899c-fb59-11e5-8b36-1e04c50b86a4.JPG)
![capture2](https://cloud.githubusercontent.com/assets/18260878/14281894/50c568b8-fb59-11e5-9ae3-d6a636b99c93.JPG)
