### ISSUE TITLE
the SIM800L resulted continue rebooting

### ISSUE THREAD

**Issue by summerfind** [stanleyhuangyc/Freematics#180]
Hi all.
the code below from: https://github.com/ahmadlogs/sim800l-gps-webserver which used software serial, some reason my IDE doesn't compiling the code with software serial (don't why), I modified it as hardware serial by simply commented out, and got keep rebooting now.
Thank for help.
Adam

`// #include <SoftwareSerial.h>

///#define rxPin 2
///#define txPin 3
///SoftwareSerial sim800L(rxPin,txPin); 

#define RXD1 1   //was 2
#define TXD1 2  // was 3 
///SoftwareSerial sim800(rxPin,txPin);
HardwareSerial neogps(1);

void setup()
{
  //Begin serial communication with Arduino and Arduino IDE (Serial Monitor)
  Serial.begin(115200);
  
  //Begin serial communication with Arduino and SIM800L
 // sim800.begin(9600);
  neogps.begin(9600, SERIAL_8N1, RXD1, TXD1);

  Serial.println("Initializing...");
  delay(1000);
}

void loop()
{
  while(neogps.available()){
    Serial.println(neogps.readString());
  }
  while(Serial.available())  {
    neogps.println(Serial.readString());
  }
}

/*
AT
Check Sim is ready or not
AT+CPIN?
 */`

**Comment by stanleyhuangyc** [comment]
Sorry SIM800 is no longer supported in this project.
