### ISSUE TITLE
firmware_v5/datalogger corrupted after enabling BLE

### ISSUE THREAD

**Issue by PonomarovP** [stanleyhuangyc/Freematics#182]
I have bought Freematics ONE+ Model B and trying to repeat steps described in [Using Freematics ONE and ONE+ with Freematics Controller App.](https://blog.freematics.com/2022/freematics-one-plus-freematics-controller-app/)
I've downloaded sketches, installed Freematics Builder and mobile app. I've successfully built and uploaded default datalogger sketch into OBD-adapter. Next step according to the guide is to change ENABLE_BLE from 0 to 1 in config.h. After this step build and upload complete successfully, but the adapter keeps rebooting with following message:

> CPU:160MHz FLASH:16MB
> 
> IRAM:268KB
> Guru Meditation Error: Core  0 panic'ed (Interrupt wdt timeout on CPU0). 
> 
> Core  0 register dump:
> PC      : 0x4008f998  PS      : 0x00060035  A0      : 0x40080206  A1      : 0x3ffd12e0  
> A2      : 0x3ffd03d8  A3      : 0x3f401b2a  A4      : 0x00000014  A5      : 0x00060023  
> A6      : 0x00060023  A7      : 0x00000001  A8      : 0x000000a5  A9      : 0x000000a5  
> A10     : 0x00000013  A11     : 0x00000001  A12     : 0x00060021  A13     : 0x3ffd13a0  
> A14     : 0x007be818  A15     : 0x003fffff  SAR     : 0x00000006  EXCCAUSE: 0x00000005  
> EXCVADDR: 0x00000000  LBEG    : 0x40090bf0  LEND    : 0x40090bfb  LCOUNT  : 0xffffffff  
> 
> 
> Backtrace:0x4008f995:0x3ffd12e00x40080203:0x3ffd1300 0x40093d00:0x3ffd1330 0x40093cb0:0x00060d23  |<-CORRUPTED
> 
> 
> Core  1 register dump:
> PC      : 0x400967f7  PS      : 0x00060035  A0      : 0x800955ac  A1      : 0x3ffbd760  
> A2      : 0x3ffbe818  A3      : 0xb33fffff  A4      : 0x0000cdcd  A5      : 0x00060023  
> A6      : 0x00060023  A7      : 0x0000abab  A8      : 0x0000cdcd  A9      : 0xffffffff  
> A10     : 0x00000003  A11     : 0x00060023  A12     : 0x80082172  A13     : 0x3ffbe76c  
> A14     : 0x007be818  A15     : 0x003fffff  SAR     : 0x00000000  EXCCAUSE: 0x00000005  
> EXCVADDR: 0x00000000  LBEG    : 0x00000000  LEND    : 0x00000000  LCOUNT  : 0x00000000  
> 
> 
> Backtrace:0x400967f4:0x3ffbd7600x400955a9:0x3ffbd7a0 0x40093d00:0x3ffbd7d0 0x40093cb0:0xa5a5a5a5  |<-CORRUPTED
> 
> ELF file SHA256: 0000000000000000
> 
> Rebooting...
> ets Jun  8 2016 00:22:57
> 
> rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
> configsip: 0, SPIWP:0xee
> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
> mode:DIO, clock div:2
> load:0x3fff0030,len:1324
> ho 0 tail 12 room 4
> load:0x40078000,len:13508
> load:0x40080400,len:3604
> entry 0x400805f0
> CPU:160MHz FLASH:16MB
> IRAM:268KB
> Guru Meditation Error: Core  0 panic'ed (Interrupt wdt timeout on CPU0). 
> 
> Core  0 register dump:
> PC      : 0x40080200  PS      : 0x00060035  A0      : 0x80095678  A1      : 0x3ffd12e0  
> A2      : 0x3ffd03d8  A3      : 0x3f401b2a  A4      : 0x00000014  A5      : 0x00060023  
> A6      : 0x00060023  A7      : 0x00000001  A8      : 0x000000a5  A9      : 0x000000a5  
> A10     : 0x00000003  A11     : 0x00000001  A12     : 0x00060021  A13     : 0x3ffd13a0  
> A14     : 0x007be818  A15     : 0x003fffff  SAR     : 0x00000006  EXCCAUSE: 0x00000005  
> EXCVADDR: 0x00000000  LBEG    : 0x40090bf0  LEND    : 0x40090bfb  LCOUNT  : 0xffffffff  
> 
> 
> Backtrace:0x400801fd:0x3ffd12e00x40095675:0x3ffd1300 0x40093d00:0x3ffd1330 0x40093cb0:0x00060d23  |<-CORRUPTED
> 
> 
> Core  1 register dump:
> PC      : 0x400967ef  PS      : 0x00060035  A0      : 0x800955ac  A1      : 0x3ffbd760  
> A2      : 0x3ffbe818  A3      : 0xb33fffff  A4      : 0x0000cdcd  A5      : 0x00060023  
> A6      : 0x00060023  A7      : 0x0000abab  A8      : 0x0000cdcd  A9      : 0xffffffff  
> A10     : 0x00000003  A11     : 0x00060023  A12     : 0x80082172  A13     : 0x3ffbe76c  
> A14     : 0x007be818  A15     : 0x003fffff  SAR     : 0x00000000  EXCCAUSE: 0x00000005  
> EXCVADDR: 0x00000000  LBEG    : 0x00000000  LEND    : 0x00000000  LCOUNT  : 0x00000000  
> 
> 
> Backtrace:0x400967ec:0x3ffbd7600x400955a9:0x3ffbd7a0 0x40093d00:0x3ffbd7d0 0x40093cb0:0xa5a5a5a5  |<-CORRUPTED
> 
> 
> ELF file SHA256: 0000000000000000
> 
> Rebooting...

Addresses in backtrace differ each reboot. Is it something with my device or guide outdated?

**Comment by stanleyhuangyc** [comment]
Please compile with PlatformIO or Arduino IDE if you need to use BLE.
