### ISSUE TITLE
Use SD card as buffer

### ISSUE THREAD

**Issue by arduino-man** [stanleyhuangyc/Freematics#185]
Hi everyone,

In the Telelogger V5 example, is it possible to use the SD card as the buffer?

I have a situation where vehicles may be out of WIFI coverage (no cell signal in this area) for several hours and the SD card seems like the perfect place to buffer location data until signal is restored rather than using PSRAM.

Thanks

**Comment by stanleyhuangyc** [comment]
Welcome to contribute this feature.
