### ISSUE TITLE
could you provide schematics file for Esprit-c3?

### ISSUE THREAD

**Issue by chaoyangnz** [stanleyhuangyc/Freematics#188]
This is a new board I recently bought, but I am unable to find the schematics file, the only image in the product page doesn't match the board.

Nice to provide a schematics file so that I know how to write bare metal program on it.

Thanks

**Comment by stanleyhuangyc** [comment]
There is a link to schematics PDF on the bottom of product page.
https://freematics.com/store/index.php?route=product/product&product_id=100

**Comment by chaoyangnz** [comment]
Thanks. awesome
