### ISSUE TITLE
A bug and a meaningless(?) calculation

### ISSUE THREAD

**Issue by Bluebrain2000** [stanleyhuangyc/Freematics#195]
in: firmware_v5/telelogger/telelogger.ino
line 301
```
if ((lastGPSLat || lastGPSLng) && (abs(gd->lat - lastGPSLat) > 0.001 || abs(gd->lng - lastGPSLng > 0.001))) {
  // invalid coordinates data
```

**1st:** a bracket is wrong at the end, this should be
`abs(gd->lng - lastGPSLng) > 0.001`
instead of
`abs(gd->lng - lastGPSLng > 0.001)`

**2nd:** Why is it assumed that the GPS coordinates are invalid if they have differed by more than 0.001 since the last position?
Then all data would be treated as invalid if the vehicle is in motion, since the GPS coordinates are constantly changing.

**Comment by stanleyhuangyc** [comment]
Thanks. Fixed.
