### ISSUE TITLE
wire.h esp32

### ISSUE THREAD

**Issue by gbredakis** [stanleyhuangyc/Freematics#207]
seems like i cant find the library wire.h. I want to load a new code but the compilation "breaks" upon searching wire.h

**Comment by stanleyhuangyc** [comment]
That is part of Arduino core.

**Comment by gbredakis** [comment]
Is it possible to use dual screen( different measures one its screen)?
Thank you !

Στις Παρ 13 Δεκ 2024 στις 12:19 πμ ο χρήστης Stanley Huang <
***@***.***> έγραψε:
