### ISSUE TITLE
minor bug in logger code

### ISSUE THREAD

**Issue by hayden-t** [stanleyhuangyc/Freematics#8]
in config.h you state that OBD_ATTEMPTS can be set to 0 to never give up connection attempts, but that dous not happen. yur code needs to look like this instead:

`    } else if (attempts <= OBD_ATTEMPTS - 1 || !OBD_ATTEMPTS) { `

**Comment by stanleyhuangyc** [comment]
Thanks. Fix committed.

**Comment by hayden-t** [comment]
thanks
