### ISSUE TITLE
+CPSI: NO SERVICE

### ISSUE THREAD

**Issue by marrakchino** [stanleyhuangyc/Freematics#81]
Hi, 

I'm getting this error when trying to initialize the SIM5360E module on a Freematics One+ (executing `sim5360` project), as an answer to the `AT+CPSI?` command. 

For one SIM card, I get `+CPSI: NO SERVICE,Online`, when using a different one I get `+CPSI: NO SERVICE,Powering Off`

Does anyone have insights about this? 

Thanks.

**Comment by ALEEF02** [comment]
@marrakchino What was your solution for this issue?

**Comment by marrakchino** [comment]
> @marrakchino What was your solution for this issue?

I did not found any solution to this issue. I waited for a reply and closed the issue when nothing came up.

Good luck.

**Comment by PatrickStar99** [comment]
Hi.

Have you found a solution?
