### ISSUE TITLE
Issues with HTTP(S) POST request

### ISSUE THREAD

**Issue by marrakchino** [stanleyhuangyc/Freematics#83]
Hi,

I am using `sim5360` sketch to send a HTTPS POST request but have the following issues.

* When connecting to port 80 with `AT+CHTTPSOPSE=$URL,80,1`, I get the following 302 response:
```
HTTP/1.1 302 Found
Server: Cowboy
Connection: keep-alive
X-Powered-By: Express
Location: $URL
Vary: Accept
Content-Type: text/plain; charset=utf-8
Content-Length: 74
Date: Tue, 26 Feb 2019 14:59:44 GMT
Via: 1.1 vegur

Found. Redirecting to https://<same_server_address>
```

* When connecting to port 443 with `AT+CHTTPSOPSE=$URL,443,2`, I fail to connect (edit: this is normal because the remote server does not support SSL3.0).

* When connecting to port 443 with server type 1 (`AT+CHTTPSOPSE=$URL,443,1`), I connect and send data but fail to receive anything.

Does anyone have any insights? Should I use/configure SSL certificates?)
Best regards.

**Comment by dogusural** [comment]
I also have the same problem, have you managed to solve it ?

**Comment by marrakchino** [comment]
Hi Dogus,

Unfortunately I couldn't. And Stanley didn't seem to consider this a
noteworthy issue.
Good luck solving it...

Le ven. 13 mars 2020 à 16:41, Dogus Ural <notifications@github.com> a
écrit :

**Comment by dogusural** [comment]
Hi marrakchino ,

Thanks for letting me know. I will post under this post if i manage to solve it.
