### ISSUE TITLE
SD card mount failure after flashing

### ISSUE THREAD

**Issue by AndreaBorgia-Abo** [stanleyhuangyc/Freematics#90]
HW: ONE+
Sketch: DataLogger v5

About half of the times I flash a new firmware, at the next boot the SD card will fail to mount with this error:
```
ESP32 240MHz 4MB Flash
MEMS...OK
ACC Bias:0.00/-0.23/0.77
SD...[E][sd_diskio.cpp:739] sdcard_mount(): f_mount failed 0x(3)
```
Removing the card and reformatting fixes the issue for sure, perhaps just removing and reinserting it would be enough. This is a different issue than #47 

Unless there is a way to powercycle the card without removing it from the slot, a possible workaround is to [retry a few times](https://github.com/espressif/arduino-esp32/issues/2171#issuecomment-445928449).

**Comment by 6eff** [comment]
+1
