### ISSUE TITLE
datalogger, missing timestamp

### ISSUE THREAD

**Issue by AndreaBorgia-Abo** [stanleyhuangyc/Freematics#91]
Until the moment the GPS comes online and provides date and time, at present there is no timestamp for the log entries in the file.
Within each loop block, the first entry is 10D (speed) and the last is 24 (battery voltage) but no indication of time or any way to correlate it with later GPS date/time information.

**Comment by stanleyhuangyc** [comment]
Use timestamp

**Comment by AndreaBorgia-Abo** [comment]
@stanleyhuangyc I got a notification for a comment on this issue but I can't find anything. It said "use timestamp". Well, this is what my PR wanted to do but you rejected it. Was there anything wrong with it?

**Comment by stanleyhuangyc** [comment]
Timestamp is actually stored as a data set with PID=0.

**Comment by AndreaBorgia-Abo** [comment]
Datalogger is _not_ logging to CSV files: that is Telelogger you have in mind. This bug is about Datalogger.
