### ISSUE TITLE
teleserver fails to build - missing jsonconfig

### ISSUE THREAD

**Issue by wongpopy2k** [stanleyhuangyc/Freematics#95]

**Comment by agoria555** [comment]
Hello to fulfill: in teleserver Makefile,
these object files are referenced cJSON.o cJSON_Utils.o cdecode.o cencode.o jsonconfig.o, 
but no C files are present in repo for building.

**Comment by stanleyhuangyc** [comment]
These are standard cJSON library files. Anyway I'll just add these files.

**Comment by wongpopy2k** [comment]
make: *** No rule to make target `jsonconfig.o', needed by `all'.  Stop.
still hving this error...
