### ISSUE TITLE
Send request over HTTPS

### ISSUE THREAD

**Issue by quochung3993** [stanleyhuangyc/Freematics#99]
I have purchased a Freematics ONE+ Model B with module SIM7600E-H
I took me a while for using Cellular data, but I successed (verified through telelogger).

Next, I would like to know how to send request using Cellular data over HTTPS protocol ?
I have researched but cannot found any clue to do so.
(Originally, I would like to send message over MQTT, but I found no library to integrate with SIM module so I have to switch to HTTPS)

Could anyone please help me.
Thank you.

**Comment by stanleyhuangyc** [comment]
You can refer to SIM7600 AT command-set document or application notes on how to use HTTPS.
